# hi6402 dsp device driver
EXTRA_CFLAGS += -I$(BALONG_TOPDIR)/audiodsp/custom/hi6402_hifi/include/med/

obj-$(CONFIG_HI6402_HIFI_MISC) += hi6402_hifi_misc.o
obj-$(CONFIG_HI6402_HIFI_MISC) += hi6402es_hifi_misc.o
